### PR TITLE
Add v-cloak to Portfolio edit page

### PR DESCRIPTION
**Pull request by montana-mil**
## Description
A `!` was briefly showing instead of  `✓` on the name and description of a Portfolio in the Portfolio's edit page.  This PR adds a v-cloak to the portfolio edit form to prevent that render glitch.

## Pivotal Tracker
https://www.pivotaltracker.com/story/show/161959592

### CODE REVIEW

**Comment by patricksmithdds** [comment]
Should this be applied in the text input component? I'm curious if this happens everywhere we're using a text input with validation.

**Comment by montana-mil** [comment]
@patricksmithdds it might even be everywhere we are using validation on an input

**Comment by patricksmithdds** [comment]
> it might even be everywhere we are using validation on an input

Is it possible to add the `v-cloak` somewhere that applies to all of those validated inputs?

**Comment by montana-mil** [comment]
@patricksmithdds i tried to figure out a way to do that, but I'm not coming up with anything. Did you have something in mind? Is it possible?

**Comment by patricksmithdds** [comment]
> i tried to figure out a way to do that, but I'm not coming up with anything. Did you have something in mind? Is it possible?

What you did in 41e6500 is what I had in mind.

**Pull request merged**
