### PR TITLE
Fix add tf plan script

### PR DESCRIPTION
**Pull request by mikepw**
redo of last pr; 
adds `tf_plan.sh` to help w/ PR review
adds readme for scripts dir

### CODE REVIEW

**Comment by dandds** [comment]
@mikepw Are we sure this has changes we need? Could you resolve the conflicts? That will tell us what changes there are.

**Comment by papetti23** [comment]
> @mikepw Are we sure this has changes we need? Could you resolve the conflicts? That will tell us what changes there are.

conflicts didn't show up in Atom and I trusted it. Sorry for the confusion, should be good now.

**Comment by dandds** [comment]
Looks clean now but the only changes in the diff are whitespace additions. Seems like your last PR for this had all the meat. Do you think we can close?

**Comment by mikepw** [comment]
> Looks clean now but the only changes in the diff are whitespace additions. Seems like your last PR for this had all the meat. Do you think we can close?

hmmf.. ok well I guess staging is all copacetic then I'm closing this down.

**Comment by mikepw** [comment]
closing.. changes already in staging.

**Pull request closed without merging**
