### PR TITLE
adds dry run provider

### PR DESCRIPTION
**Pull request by mikepw**
Adds the dry run provider folder we used to create the dry run

### CODE REVIEW

**Comment by dandds** [comment]
@mikepw Can you add the deploy tag here and follow up in slack with values for VAULT_CLIENT_ID and VAULT_URL? Are we using the same SP as we were with pwdev?

**Comment by carleton-dds** [comment]
@mikepw Let's use some of our pairing time today to review this PR, I'm not sure I have the foundation to review it yet

**Comment by mikepw** [comment]
> @mikepw Can you add the deploy tag here and follow up in slack with values for VAULT_CLIENT_ID and VAULT_URL? Are we using the same SP as we were with pwdev?

deploy_tag: dryrun

following up on slack w/ VAULT_CLIENT_ID and VAULT_URL

SP is attached to registered app, will update in slack w/ that as well.

**Comment by jesse-dds** [comment]
Can you delete the `.DS_STORE` file in here?

**Comment by carleton-dds** [comment]
@mikepw looks like there's some merge conflicts that need some attention

**Comment by dandds** [comment]
Can you fix the merge conflicts on here @mikepw ? 🙏

**Pull request merged**
