### PR TITLE
Add README details about how to configure the application.

### PR DESCRIPTION
**Pull request by dandds**
Small change to the README to describe how config is currently applied and the various ways it can be set.

### CODE REVIEW

**Comment by dandds** [comment]
@carleton-dds Yeah, I think I would put that in the configuration section per-setting. 

One thing I'm struggling with is that some of that info (like AZURE_TENANT_ADMIN_PASSWORD) lives in our password manager _and_ Key Vault right now. We source it from the password manager when we need it to run the hybrid tests locally, but the app sources it from the Key Vault. We could transition to source it from KV, which might cut down on duplication. I am wondering if it's worthwhile to have some kind of wrapper script that can just pull the values you need and inject them into your environment when you run the hybrid tests, provided that you authenticate and have the right perms.

**Comment by carleton-dds** [comment]
@dandds A wrapper script like you describe sounds like it could be really helpful. I agree with the tension around having multiple places where config values are at rest is not great and my Google doc is also kind of exacerbating that issue. I can type up an issue if you think it'd be helpful

**Comment by dandds** [comment]
@carleton-dds The Google Doc is a big improvement over what we had, imo. Would you mind adding a ticket if you have time?

**Comment by carleton-dds** [comment]
@dandds  Issue for wrapper script https://ccpo.atlassian.net/browse/AT-5287

**Pull request merged**
